更新到了Minecraft1.20.1，添加了新功能
ImyvmCircle/Essential pull request #4
Opened 2023-06-24 16:15 UTC by Dream-Rainy

更新到了Minecraft1.20.1，添加了收税功能，同时支持ptt命令显示距离奖励还剩多少时间且支持有偿自动领取。修正了一个翻译问题。

2023-06-24 17:30 UTC, YanWQ-monad requested changes
先这样吧

2023-06-24 17:30 UTC, YanWQ-monad commented on src/main/java/com/imyvm/essential/systems/ptt/PlayTimeTrackSystem.java
> +            if (statusStr.equals("name.ptt.status.not_meet")){
```suggestion
            if (data.getStatus() == TrackData.Status.NOT_MEET) {
```

2023-06-24 17:30 UTC, YanWQ-monad commented on src/main/java/com/imyvm/essential/systems/ptt/PlayTimeTrackSystem.java
> +            String statusStr = "name.ptt.status." + data.getStatus().toString().toLowerCase();
```suggestion
            String statusTemplate = "name.ptt.status." + data.getStatus().toString().toLowerCase();
```

2023-06-24 17:30 UTC, YanWQ-monad commented on src/main/java/com/imyvm/essential/systems/ptt/PlayTimeTrackSystem.java
> +                    default -> status = tr("name.ptt.status.continuous");
```suggestion
                status = tr(statusStr, TimeUtil.formatDuration(counter.getTimeRequired() - duration));
```

然后给 `TimeCounter` 加一个 getter `getTimeRequired()`

然后记得把 `DurationConstants` 删了

2023-06-24 17:30 UTC, YanWQ-monad commented on src/main/java/com/imyvm/essential/systems/fly/PaidFlyGui.java
> +        return itemRegistry.getOrEmpty(Identifier.tryParse(id)).orElseThrow();
为啥要分两行

2023-06-24 17:30 UTC, YanWQ-monad commented on src/main/java/com/imyvm/essential/TradeTypeRegistry.java
> +        DEATHPROTECT;
```suggestion
        DEATH_PROTECT;
```

2023-06-24 17:30 UTC, YanWQ-monad commented on src/main/java/com/imyvm/essential/EssentialMod.java
> +    }
请参考 `PurchaseType` 或 `TimeCounter` 的实现，尽量避免手动解析数据

2023-06-24 17:30 UTC, YanWQ-monad commented on src/main/java/com/imyvm/essential/TradeTypeRegistry.java
> +    public enum TradeType implements TradeTypeEnum.TradeTypeExtension {
`TradeTypeRegistey` 下只有一个 `TradeType` 就没必要再包一层了吧

2023-06-24 17:30 UTC, YanWQ-monad commented on src/main/java/com/imyvm/essential/TradeTypeRegistry.java
> +        public Double getTax() {
```suggestion
        public double getTax() {
```

2023-06-24 17:30 UTC, YanWQ-monad commented on src/main/java/com/imyvm/essential/systems/ptt/BonusSupplier.java
> +                Long bonusFin = (long) (ticket.bonus * CONFIG.PTT_REISSUE_RATIO.getValue());
```suggestion
                long bonusFin = (long) (ticket.bonus * CONFIG.PTT_REISSUE_RATIO.getValue());
```

BTW，`Fin` 是什么意思

2023-06-25 06:28 UTC, Dream-Rainy commented on src/main/java/com/imyvm/essential/systems/ptt/BonusSupplier.java
> +                Long bonusFin = (long) (ticket.bonus * CONFIG.PTT_REISSUE_RATIO.getValue());
Final（

2023-06-25 06:57 UTC, YanWQ-monad commented on src/main/java/com/imyvm/essential/systems/ptt/BonusSupplier.java
> +                Long bonusFin = (long) (ticket.bonus * CONFIG.PTT_REISSUE_RATIO.getValue());
那请你写全称，两个字符都要省是吧 🌚

2023-06-25 07:06 UTC, Dream-Rainy commented
github怎么构建的时候没有同步库啊（

2023-06-27 18:20 UTC, YanWQ-monad commented
PR 更新的功能（for review）

- [ ] 游戏版本 1.19 到 1.20 到适配（不包含功能性改动），包括 API、Mixin
- [ ] 更新依赖
      大致上没什么问题，只是 `share.dreamrain.top` 的更新有点不是很规范，PR 还没合就已经上传到 repositories 了是吧（
- [ ] 税收功能，等 ImyvmEconomy PR 合并，个人不是很喜欢现在的设计
- [x] PTT 增加倒计时显示
- [ ] PTT 奖励系统的过期补发
- [x] 翻译更新

2023-06-28 09:39 UTC, closed without merging